# Generated by Django 5.0.2 on 2024-03-10 14:44

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=255)),
                ('access_level', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='product_id',
            field=models.CharField(default=products.models.generate_id, editable=False, max_length=255, unique=True),
        ),
    ]
