# Generated by Django 5.0.3 on 2024-03-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_access_level_products_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='products_issued',
            field=models.ManyToManyField(to='products.products'),
        ),
    ]
